import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowIcon } from "@/components/ArrowIcon";
import { InquiryForm } from "@/components/InquiryForm";
import { ProductCard } from "@/components/ProductCard";
import { ProductDetailPage } from "@/components/ProductDetailPage";
import { isLocale } from "@/lib/i18n";
import { getCategories, getLocalizedCategory, getLocalizedProduct, getLocalizedProductsByCategory, getProducts, type Locale } from "@/lib/products";

type Props = { params: Promise<{ locale: string; path?: string[] }>; searchParams: Promise<{ product?: string }> };
const href = (locale: Locale, path = "") => `/${locale}${path}`;

const copy = {
  en: {
    meta: "Industrial machinery parts and conveyor solutions for demanding applications.",
    home: ["Industrial supply · engineered response", "Industrial machinery parts built for reliable performance.", "Conveyor belts, power transmission products, conveyor components, rubber parts and mining spares supplied for demanding industrial applications."],
    explore: "Explore products", request: "Request a quote", productRange: "Product range", systems: "One supply partner. Six industrial systems.", rangeCopy: "Start with the equipment, application or operating condition. We help narrow the product construction and specification for quotation.",
    featured: "Featured products", ready: "Ready for your next inquiry.", viewAll: "View all products", industries: "Industry applications", industryTitle: "Parts selected around the work they need to do.", industryCopy: "Product selection begins with load, speed, temperature, material and maintenance expectations—not a generic catalog number.", exploreIndustries: "Explore industries",
    why: "Why OVBEL", whyTitle: "Practical support from product search to shipment.", start: "Start with what you know", send: "Send a part number, drawing or application.", build: "Build your inquiry",
    productCenter: "Product center", productsTitle: "Industrial products organized around your system.", productsLead: "Browse six product families, then send the specification or operating conditions needed for quotation.", catalog: "Launch catalog", catalogTitle: "13 products across six categories.",
    available: "Available range", family: "Start with a product family.", customCopy: "Need a different construction or model? Send your specification, drawing or equipment reference for review.", notSeeing: "Not seeing the exact part?", matchCopy: "OVBEL supports custom and cross-reference inquiries.", match: "Request a match",
    features: "Features", built: "Built around the application.", technical: "Technical overview", specNote: "Final specification is confirmed against the application before quotation.", applications: "Applications", where: "Where this product works.", ask: "Ask a question", productInquiry: "Product inquiry", discuss: "Discuss product requirements.", sendRequirements: "Send requirements",
  },
  zh: {
    meta: "面向严苛工业应用的机械配件与输送解决方案。",
    home: ["工业供应 · 工程响应", "为可靠运行而生的工业机械配件。", "为严苛工业应用提供输送带、动力传动产品、输送机配件、橡胶制品和矿山备件。"],
    explore: "浏览产品", request: "获取报价", productRange: "产品范围", systems: "一个供应伙伴，六大工业系统。", rangeCopy: "从设备、应用或工况出发，我们协助确定适合报价的产品结构与规格。",
    featured: "精选产品", ready: "为您的下一次询盘做好准备。", viewAll: "查看全部产品", industries: "行业应用", industryTitle: "围绕实际任务选择合适配件。", industryCopy: "产品选型从载荷、速度、温度、物料和维护要求出发，而不是只看通用目录编号。", exploreIndustries: "查看应用行业",
    why: "选择 OVBEL", whyTitle: "从产品查找到装运交付的务实支持。", start: "从现有信息开始", send: "发送零件号、图纸或应用要求。", build: "填写询盘",
    productCenter: "产品中心", productsTitle: "围绕工业系统组织的产品目录。", productsLead: "浏览六大产品系列，并提交报价所需的规格或工作条件。", catalog: "首批目录", catalogTitle: "六大分类，共 13 款产品。",
    available: "可选范围", family: "从产品系列开始。", customCopy: "需要其他结构或型号？请发送规格、图纸或设备信息供我们审核。", notSeeing: "没有找到完全匹配的零件？", matchCopy: "OVBEL 支持定制和型号交叉匹配询盘。", match: "申请匹配",
    features: "产品特点", built: "围绕实际应用设计。", technical: "技术概览", specNote: "最终规格将在报价前根据具体应用确认。", applications: "应用场景", where: "适用领域。", ask: "咨询问题", productInquiry: "产品询盘", discuss: "讨论产品需求。", sendRequirements: "发送需求",
  },
} as const;

const industryData = {
  en: [["Mining & Quarry", "Wear, impact and screening components for abrasive production environments."], ["Material Handling", "Belting and conveyor components designed around dependable material flow."], ["Manufacturing", "Transmission, rubber and rotating parts for processing and factory equipment."], ["Food & Grain", "Elevator, belting and power-transmission products for controlled handling."]],
  zh: [["矿山与采石", "适用于高磨蚀生产环境的耐磨、缓冲和筛分配件。"], ["物料输送", "围绕稳定物料流设计的输送带和输送机配件。"], ["制造加工", "适用于加工和工厂设备的传动、橡胶及旋转部件。"], ["食品与粮食", "用于受控输送的提升、输送带和动力传动产品。"]],
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale: raw, path = [] } = await params;
  if (!isLocale(raw)) return {};
  const locale = raw;
  const product = path[0] === "products" && path.length === 3 ? getLocalizedProduct(path[1], path[2], locale) : undefined;
  const category = path[0] === "products" && path.length === 2 ? getLocalizedCategory(path[1], locale) : undefined;
  const title = product?.seo?.title || product?.name || category?.name || (locale === "zh" ? "OVBEL 工业机械配件" : "OVBEL Industrial Machinery Parts");
  const description = product?.seo?.description || product?.summary || category?.summary || copy[locale].meta;
  const canonical = `https://ovbel.com/${locale}${path.length ? `/${path.join("/")}` : ""}`;
  const alternatePath = path.length ? `/${path.join("/")}` : "";
  const ogImages = product?.media ? [product.media.cover, ...product.media.gallery].filter((image): image is string => Boolean(image)).map((image) => `https://ovbel.com${image}`) : [];
  return { title, description, alternates: { canonical, languages: { "en": `https://ovbel.com/en${alternatePath}`, "zh-CN": `https://ovbel.com/zh${alternatePath}`, "x-default": `https://ovbel.com/en${alternatePath}` } }, openGraph: { title, description, url: canonical, ...(ogImages.length ? { images: ogImages } : {}) } };
}

function Home({ locale }: { locale: Locale }) {
  const t = copy[locale], categories = getCategories(locale), products = getProducts(locale);
  const values = locale === "zh" ? [["广泛的产品范围", "在一次询盘中协调输送带、输送机、橡胶、矿山和驱动产品。"], ["OEM 与定制", "根据尺寸、图纸、设备数据和目标工况匹配供应。"], ["质量导向", "在订单流程中落实规格审核、生产协调和文件管理。"], ["出口支持", "为经销商、进口商和工业项目团队提供商务与包装支持。"]] : [["Broad product scope", "Belting, conveyor, rubber, mining and drive categories coordinated in one inquiry."], ["OEM & custom", "Supply matched to dimensions, drawings, equipment data and target operating conditions."], ["Quality focus", "Specification review, production coordination and documentation built into the order process."], ["Export experience", "Commercial and packaging support for distributors, importers and industrial project teams."]];
  return <><section className="hero"><div className="hero-grid-overlay"/><div className="shell hero-inner"><div className="hero-copy"><p className="eyebrow eyebrow-light">{t.home[0]}</p><h1>{t.home[1]}</h1><p className="hero-lead">{t.home[2]}</p><div className="button-row"><Link className="button" href={href(locale,"/products")}>{t.explore}</Link><Link className="button button-outline-light" href={href(locale,"/request-quote")}>{t.request}</Link></div></div><div className="hero-machine" aria-hidden="true"><div className="machine-rail rail-one"><i/><i/><i/></div><div className="machine-rail rail-two"><i/><i/><i/><i/></div><div className="machine-pulley pulley-one"/><div className="machine-pulley pulley-two"/><span>OV</span></div></div><div className="shell hero-stats"><div><strong>06</strong><span>{locale === "zh" ? "产品系列" : "Product families"}</span></div><div><strong>13</strong><span>{locale === "zh" ? "首批产品" : "Launch products"}</span></div><div><strong>OEM</strong><span>{locale === "zh" ? "定制供应支持" : "Custom supply support"}</span></div><div><strong>B2B</strong><span>{locale === "zh" ? "全球工业采购商" : "Global industrial buyers"}</span></div></div></section>
  <section className="section shell"><div className="section-heading split-heading"><div><p className="eyebrow">{t.productRange}</p><h2>{t.systems}</h2></div><p>{t.rangeCopy}</p></div><div className="category-grid">{categories.map(c=><Link className={`category-card tone-${c.color}`} href={href(locale,`/products/${c.slug}`)} key={c.slug}><span className="category-index">{c.index}</span><div><h3>{c.name}</h3><p>{c.summary}</p></div><ArrowIcon/></Link>)}</div></section>
  <section className="section section-gray"><div className="shell"><div className="section-heading split-heading"><div><p className="eyebrow">{t.featured}</p><h2>{t.ready}</h2></div><Link className="text-link" href={href(locale,"/products")}>{t.viewAll} <ArrowIcon/></Link></div><div className="product-grid">{products.slice(0,6).map(p=><ProductCard product={p} locale={locale} key={p.slug}/>)}</div></div></section>
  <section className="section industries-section"><div className="shell industries-grid"><div className="industries-intro"><p className="eyebrow eyebrow-light">{t.industries}</p><h2>{t.industryTitle}</h2><p>{t.industryCopy}</p><Link className="button" href={href(locale,"/industries")}>{t.exploreIndustries}</Link></div><div className="industry-list">{industryData[locale].map(([name,desc],i)=><article key={name}><span>0{i+1}</span><div><h3>{name}</h3><p>{desc}</p></div></article>)}</div></div></section>
  <section className="section shell why-grid"><div><p className="eyebrow">{t.why}</p><h2>{t.whyTitle}</h2></div><div className="value-grid">{values.map(([title,body],i)=><article key={title}><strong>0{i+1}</strong><h3>{title}</h3><p>{body}</p></article>)}</div></section>
  <section className="cta-section"><div className="shell cta-inner"><div><p className="eyebrow eyebrow-light">{t.start}</p><h2>{t.send}</h2></div><Link className="button" href={href(locale,"/request-quote")}>{t.build} <ArrowIcon/></Link></div></section></>;
}

function ProductsPage({ locale }: { locale: Locale }) { const t=copy[locale], categories=getCategories(locale), products=getProducts(locale); return <><section className="page-hero"><div className="shell"><p className="eyebrow eyebrow-light">{t.productCenter}</p><h1>{t.productsTitle}</h1><p>{t.productsLead}</p></div></section><section className="section shell"><div className="category-strip">{categories.map(c=><Link href={href(locale,`/products/${c.slug}`)} key={c.slug}><span>{c.index}</span>{c.name}<ArrowIcon/></Link>)}</div><div className="section-heading"><p className="eyebrow">{t.catalog}</p><h2>{t.catalogTitle}</h2></div><div className="product-grid">{products.map(p=><ProductCard product={p} locale={locale} key={p.slug}/>)}</div></section></>; }

function CategoryPage({ locale, slug }: { locale: Locale; slug: string }) { const t=copy[locale], category=getLocalizedCategory(slug,locale); if(!category) notFound(); const products=getLocalizedProductsByCategory(slug,locale); return <><section className={`page-hero category-hero tone-${category.color}`}><div className="shell"><p className="eyebrow eyebrow-light">{t.productCenter} / {category.index}</p><h1>{category.name}</h1><p>{category.summary}</p></div></section><section className="section shell"><div className="section-heading split-heading"><div><p className="eyebrow">{t.available}</p><h2>{t.family}</h2></div><p>{t.customCopy}</p></div><div className="product-grid product-grid-two">{products.map(p=><ProductCard product={p} locale={locale} key={p.slug}/>)}</div><div className="inline-cta"><div><h2>{t.notSeeing}</h2><p>{t.matchCopy}</p></div><Link className="button" href={href(locale,"/request-quote")}>{t.match}</Link></div></section></>; }

function ProductPage({locale,categorySlug,slug}:{locale:Locale;categorySlug:string;slug:string}) { const product=getLocalizedProduct(categorySlug,slug,locale), category=getLocalizedCategory(categorySlug,locale); if(!product||!category) notFound(); return <ProductDetailPage product={product} category={category} locale={locale}/>; }

const staticPages = {
  about: {
    en: ["About OVBEL","An industrial product partner based in Linyi, China.","OVBEL connects product knowledge, manufacturing coordination and export support for industrial buyers worldwide.","Our company","Quality first. Practical support. Long-term cooperation.","OVBEL is operated by Shandong Ovbel Industrial Co., Ltd., an industrial enterprise located in Linyi, Shandong Province, China.","The company works across product design, manufacturing coordination, marketing, installation and commissioning. Its scope covers conveyor belts, components, rubber products, hoses, mining spares, motors and drive equipment.","Work with OVBEL","Build a dependable industrial supply relationship.","Contact our team"],
    zh: ["关于 OVBEL","立足中国临沂的工业产品合作伙伴。","OVBEL 为全球工业采购商连接产品知识、制造协调和出口支持。","我们的公司","质量第一，务实支持，长期合作。","OVBEL 由山东奥贝尔工业有限公司（Shandong Ovbel Industrial Co., Ltd.）运营，公司位于中国山东省临沂市。","公司业务涵盖产品设计、制造协调、营销、安装与调试，产品范围包括输送带、输送机配件、工业橡胶制品、胶管、矿山备件、电机与驱动设备。","与 OVBEL 合作","建立可靠的工业供应关系。","联系我们"],
  },
  contact: {
    en: ["Contact","Start an industrial product conversation.","Share the product, equipment or operating condition. We will help organize the information needed for quotation.","Company","For a faster response","Product name, model or OEM number","Dimensions, material or drawing","Application and operating conditions","Required quantity and destination country","Prepare an inquiry"],
    zh: ["联系我们","开启一次工业产品沟通。","请提供产品、设备或工作条件，我们将协助整理报价所需信息。","公司","为了更快获得回复","产品名称、型号或 OEM 编号","尺寸、材料或图纸","应用与工作条件","需求数量和目的国家","准备询盘"],
  },
};

function About({locale}:{locale:Locale}) { const x=staticPages.about[locale]; return <><section className="page-hero"><div className="shell"><p className="eyebrow eyebrow-light">{x[0]}</p><h1>{x[1]}</h1><p>{x[2]}</p></div></section><section className="section shell editorial-grid"><div><p className="eyebrow">{x[3]}</p><h2>{x[4]}</h2></div><div className="prose"><p>{x[5]}</p><p>{x[6]}</p><p>{locale==="zh"?"研发、生产、销售和服务团队为生产、检测与质量控制提供支持，合适的产品与项目可提供 OEM 和 ODM 服务。":"Production, testing and control capabilities are supported by R&D, production, sales and service teams. OEM and ODM supply is available for suitable products and projects."}</p></div></section><section className="cta-section"><div className="shell cta-inner"><div><p className="eyebrow eyebrow-light">{x[7]}</p><h2>{x[8]}</h2></div><Link className="button" href={href(locale,"/contact")}>{x[9]}</Link></div></section></>; }
function Contact({locale}:{locale:Locale}) { const x=staticPages.contact[locale]; return <><section className="page-hero"><div className="shell"><p className="eyebrow eyebrow-light">{x[0]}</p><h1>{x[1]}</h1><p>{x[2]}</p></div></section><section className="section shell contact-grid"><div><p className="eyebrow">{x[3]}</p><h2>Shandong Ovbel Industrial Co., Ltd.</h2><p>{locale==="zh"?"中国山东省临沂市":"Linyi, Shandong Province, China"}</p><div className="contact-block"><span>{locale==="zh"?"销售邮箱（规划）":"Planned sales email"}</span><a href="mailto:info@ovbel.com">info@ovbel.com</a></div><div className="contact-block"><span>{locale==="zh"?"网站":"Website"}</span><a href="https://ovbel.com">ovbel.com</a></div></div><div className="contact-panel"><h2>{x[4]}</h2><ul className="check-list">{x.slice(5,9).map(i=><li key={i}>{i}</li>)}</ul><Link className="button" href={href(locale,"/request-quote")}>{x[9]}</Link></div></section></>; }

function Industries({locale}:{locale:Locale}) { const data=locale==="zh"?[["矿山与采石","适用于开采、破碎和骨料生产的耐磨、缓冲及筛分配件。","钢丝绳芯和防撕裂输送带 · 缓冲床 · 破碎机锤头 · 筛网"],["物料输送与物流","支持转运、仓储和配送系统稳定物流的输送带与配件。","粗面输送带 · 托辊 · 滚筒 · 清扫器 · 防护罩"],["制造与加工","面向产线设备、车间系统和加工机械的传动及旋转部件。","V 带 · 同步带 · 轴承 · 电机 · 橡胶制品"],["食品与粮食加工","用于粮食和食品物料受控处理的提升、输送和动力传动产品。","白色输送带 · 提升机料斗 · 平带 · 花纹带"]]:[["Mining & Quarry","Wear, impact and screening components for extraction, crushing and aggregate production.","Steel cord and anti-tear belts · Impact beds · Crusher hammers · Screen mesh"],["Material Handling & Logistics","Belting and components that support stable product flow through transfer, storage and distribution systems.","Rough top belts · Rollers · Pulleys · Belt cleaners · Conveyor covers"],["Manufacturing & Processing","Transmission and rotating components selected for line equipment, workshop systems and process machinery.","V-belts · Timing belts · Bearings · Motors · Rubber products"],["Food & Grain Processing","Elevator, conveying and power-transmission products for controlled handling of grain and food materials.","White belts · Elevator buckets · Flat belts · Chevron belts"]]; return <><section className="page-hero"><div className="shell"><p className="eyebrow eyebrow-light">{locale==="zh"?"应用行业":"Industries"}</p><h1>{locale==="zh"?"从工作环境出发。":"Start with the operating environment."}</h1><p>{locale==="zh"?"我们围绕物料、载荷、工作周期和维护需求组织产品方案，而不只是目录名称。":"We organize the product conversation around material, load, duty cycle and maintenance—not just a catalog label."}</p></div></section><section className="section shell industry-page-grid">{data.map((x,i)=><article key={x[0]}><span>0{i+1}</span><h2>{x[0]}</h2><p>{x[1]}</p><small>{x[2]}</small></article>)}</section><section className="cta-section"><div className="shell cta-inner"><div><p className="eyebrow eyebrow-light">{locale==="zh"?"应用支持":"Application support"}</p><h2>{locale==="zh"?"告诉我们设备需要完成什么任务。":"Tell us what the equipment needs to do."}</h2></div><Link className="button" href={href(locale,"/request-quote")}>{locale==="zh"?"讨论您的应用":"Discuss your application"}</Link></div></section></>; }

function ServicePage({locale,type}:{locale:Locale;type:"oem"|"quality"}) { const zh=locale==="zh"; const isOem=type==="oem"; const title=isOem?(zh?"从参考零件到可供货规格。":"From a reference part to a supply-ready specification."):(zh?"质量始于生产之前。":"Quality begins before production."); const lead=isOem?(zh?"通过图纸、尺寸、样品或设备信息发起定制工业配件询盘。":"Use drawings, measurements, samples or equipment information to start a custom industrial-parts inquiry."):(zh?"清晰的规格、适当的检验和装运文件可降低工业供应过程中的风险。":"Clear specifications, relevant checks and shipment documentation reduce risk across the industrial supply process."); const items=isOem?(zh?[["分享需求","发送图纸、尺寸、参考产品、设备型号或工况。"],["审核确认","确认技术细节、材料、结构、数量和文件要求。"],["样品或报价","确定标准供应、样品验证或定制生产方案。"],["生产与交付","发货前协调质量控制点、包装和运输要求。"]]:[["Share the requirement","Send a drawing, dimensions, reference product, equipment model or conditions."],["Review and clarify","Align material, construction, quantity and documentation."],["Sample or quotation","Confirm standard supply, sample verification or custom production."],["Production and delivery","Coordinate quality, packaging and shipment before dispatch."]]):(zh?[["规格审核","确认产品、应用和关键技术参数。"],["生产控制","协调约定的材料、结构和工艺要求。"],["检验","执行适合产品的尺寸、外观和文件检查。"],["包装审核","发货前核对标识、防护和出口包装。"]]:[["Specification review","Confirm product identity, application and critical values."],["Production control","Coordinate agreed materials, construction and process requirements."],["Inspection","Apply dimensional, visual and document checks."],["Packing review","Verify markings, protection and export packing."]]); return <><section className="page-hero"><div className="shell"><p className="eyebrow eyebrow-light">{isOem?(zh?"OEM 与定制":"OEM & custom"):(zh?"质量控制":"Quality control")}</p><h1>{title}</h1><p>{lead}</p></div></section><section className="section shell"><div className="section-heading"><p className="eyebrow">{isOem?(zh?"工作流程":"Working process"):(zh?"质量第一":"Quality first")}</p><h2>{isOem?(zh?"从询盘到交付的清晰路径。":"A clear path from inquiry to delivery."):(zh?"控制影响适配、工况和寿命的细节。":"Control the details that affect fit, duty and service life.")}</h2></div><div className={isOem?"process-grid":"quality-grid"}>{items.map((x,i)=><article key={x[0]}><strong>0{i+1}</strong><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div><div className="inline-cta"><div><h2>{zh?"准备好图纸或需求了吗？":"Ready to share your requirements?"}</h2><p>{zh?"发送已有信息，我们将确认还需要哪些资料。":"Send what you have and we will identify what is still needed."}</p></div><Link className="button" href={href(locale,"/request-quote")}>{zh?"开始询盘":"Start an inquiry"}</Link></div></section></>; }

function Quote({locale,product}:{locale:Locale;product:string}) { const zh=locale==="zh"; const selectedProduct=getProducts(locale).find(item=>item.slug===product); const items=selectedProduct?.inquiryChecklist ?? (zh?["产品或设备信息","尺寸与结构","材料或性能要求","数量与目的地","照片、图纸或现有数据表"]:["Product or equipment reference","Dimensions and construction","Material or performance requirement","Quantity and destination","Photos, drawings or existing datasheets"]); return <><section className="page-hero"><div className="shell"><p className="eyebrow eyebrow-light">{zh?"获取报价":"Request a quote"}</p><h1>{zh?"分享您已有的信息。":"Share the details you already have."}</h1><p>{zh?"产品名称、型号、图纸或应用信息都可以作为沟通的起点。":"A product name, model, drawing or application is enough to start the conversation."}</p></div></section><section className="section shell quote-grid"><div><p className="eyebrow">{zh?"询盘清单":"Inquiry checklist"}</p><h2>{selectedProduct?.name ?? (zh?"有用的信息":"Useful information")}</h2><ul className="check-list">{items.map(i=><li key={i}>{i}</li>)}</ul></div><InquiryForm defaultProduct={selectedProduct?.name ?? product.replaceAll("-"," ")} productSlug={selectedProduct?.slug ?? product} locale={locale}/></section></>; }

export default async function LocalePage({params,searchParams}:Props) { const {locale:raw,path=[]}=await params; if(!isLocale(raw)) notFound(); const locale=raw; if(path.length===0) return <Home locale={locale}/>; if(path[0]==="products"&&path.length===1) return <ProductsPage locale={locale}/>; if(path[0]==="products"&&path.length===2) return <CategoryPage locale={locale} slug={path[1]}/>; if(path[0]==="products"&&path.length===3) return <ProductPage locale={locale} categorySlug={path[1]} slug={path[2]}/>; if(path.length===1){ if(path[0]==="about")return <About locale={locale}/>; if(path[0]==="contact")return <Contact locale={locale}/>; if(path[0]==="industries")return <Industries locale={locale}/>; if(path[0]==="oem-service")return <ServicePage locale={locale} type="oem"/>; if(path[0]==="quality")return <ServicePage locale={locale} type="quality"/>; if(path[0]==="request-quote"){const q=await searchParams;return <Quote locale={locale} product={q.product||""}/>;} } notFound(); }
